name: MapKitDemoGenerated

options:
  minimumXcodeGenVersion: 2.37.0
  createIntermediateGroups: true
  groupSortPosition: top
  groupOrdering: 
    - order: [Sources, Resources, Tests, Packages, Frameworks, Products]

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 13.0
    TARGETED_DEVICE_FAMILY: 1

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.6.0

configFiles:
  Debug: Sources/Resources/Configs/YMKConfig.xcconfig
  Release: Sources/Resources/Configs/YMKConfig.xcconfig

targets:
  Full:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    info:
      path: Sources/Resources/Generated/FullInfo.generated.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: 6.0
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: ${MARKETING_VERSION}
        CFBundleVersion: ${CURRENT_PROJECT_VERSION}
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconName: AppIcon-Full
            CFBundleIconFiles:
              - AppIcon-Full
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        yandex.maps.runtime.logging.Level: Error
        YMKApiKey: $(YMK_API_KEY)
    settings:
      base:
        INFOPLIST_FILE: Sources/Resources/Generated/FullInfo.generated.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yandex.maps.ymkdemo
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Full
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        OTHER_LDFLAGS: $(inherited) -ObjC -l"c++" -l"resolv" -framework "CoreFoundation" -framework "CoreGraphics" -framework "CoreLocation" -framework "CoreMotion" -framework "CoreTelephony" -framework "Foundation" -framework "OpenGLES" -framework "QuartzCore" -framework "Security" -framework "SystemConfiguration" -framework "UIKit" -framework "YandexMapsMobile"
    sources:
       - path: Sources
         excludes:
          - "**/.gitkeep"
          - "Feature/Lite/Feed"
    dependencies:
        - package: SnapKit
        - framework: Frameworks/YandexMapsMobile-4.4.0-full.xcframework

  Lite:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    info:
      path: Sources/Resources/Generated/LiteInfo.generated.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: 6.0
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: ${MARKETING_VERSION}
        CFBundleVersion: ${CURRENT_PROJECT_VERSION}
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconName: AppIcon-Lite
            CFBundleIconFiles:
              - AppIcon-Lite
            UIPrerenderedIcon: NO
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        yandex.maps.runtime.logging.Level: Error
        YMKApiKey: $(YMK_API_KEY)
    settings:
      base:
        INFOPLIST_FILE: Sources/Resources/Generated/LiteInfo.generated.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yandex.maps.ymkdemo
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Lite
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        OTHER_LDFLAGS: $(inherited) -ObjC -l"c++" -l"resolv" -framework "CoreFoundation" -framework "CoreGraphics" -framework "CoreLocation" -framework "CoreMotion" -framework "CoreTelephony" -framework "Foundation" -framework "OpenGLES" -framework "QuartzCore" -framework "Security" -framework "SystemConfiguration" -framework "UIKit" -framework "YandexMapsMobile"
    sources:
       - path: Sources
         excludes:
          - "**/.gitkeep"
          - "Feature/Full"
    dependencies:
        - package: SnapKit
        - framework: Frameworks/YandexMapsMobile-4.4.0-lite.xcframework